import { GoogleGenAI } from "@google/genai";
import { PRODUCT_SHOT_PROMPT } from "../types";

// Initialize the client. 
// Note: In a real production app, you might proxy this through a backend to protect the key,
// but for this demo/SPA environment, we access the env variable directly.
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

/**
 * Converts a base64 string (with header) to the format required by the API.
 */
const prepareImagePart = (base64Data: string, mimeType: string) => {
  // Remove the data URL prefix (e.g., "data:image/jpeg;base64,")
  const base64Content = base64Data.split(',')[1];
  return {
    inlineData: {
      data: base64Content,
      mimeType: mimeType,
    },
  };
};

export const generateProductShot = async (
  base64Image: string,
  mimeType: string
): Promise<string> => {
  try {
    const imagePart = prepareImagePart(base64Image, mimeType);
    
    // Using 'gemini-2.5-flash-image' as per "nano banana" instructions
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          imagePart,
          { text: PRODUCT_SHOT_PROMPT }
        ]
      }
    });

    // Check for image parts in the response
    const candidates = response.candidates;
    if (candidates && candidates.length > 0) {
      const parts = candidates[0].content.parts;
      for (const part of parts) {
        if (part.inlineData) {
            return `data:image/png;base64,${part.inlineData.data}`;
        }
      }
      
      // If no image part is found, check for text (error message from model)
      for (const part of parts) {
        if (part.text) {
           throw new Error(`Model returned text instead of image: ${part.text}`);
        }
      }
    }

    throw new Error("No image generated by the model.");

  } catch (error: any) {
    console.error("Gemini API Error:", error);
    throw new Error(error.message || "Failed to process image.");
  }
};
